### ISSUE TITLE
PHP Error in plugin 1.5.10

### ISSUE THREAD

**Issue by chrisatomix** [fatzebra/FatZebra-WooCommerce#10]
The following code in class-wc-fatzebra.php on line 246:

``` php
      if ($this->direct_post_enabled()) {
        $this->supports = array_push($this->supports, 'tokenization');
      }
```

generates the following error on the checkout:

```
Warning: in_array() expects parameter 2 to be array, integer given in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 359
```

As documented, array_push does not return the array itself:
http://php.net/manual/en/function.array-push.php
It returns the number of elements in the array.

The correct code should be:

``` php
      if ($this->direct_post_enabled()) {
        array_push($this->supports, 'tokenization');
      }
```

**Comment by amasses** [comment]
Hi Chris,

Thanks for raising this issue. I am arranging a fix now.

Regards,
Matthew
