### ISSUE TITLE
Direct Post not working correctly

### ISSUE THREAD

**Issue by chrisatomix** [fatzebra/FatZebra-WooCommerce#5]
There have been several issues with Direct Post in this plugin.
1. The name of the card token field was referenced incorrectly, causing Direct Post not to work
2. Changing the credit card details after a failed transaction did not trigger a new tokenization

I have submitted a PR with the fixes I applied: #4

**Comment by amasses** [comment]
Thanks for the issue and PR and sorry its taken so long to merge this in. I'm pushing an update to Wordpress shortly.
